oicr-gsi/pinery

- pinery-lims-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java
~~Will likely need redirected into a RC7 branch~~
> correct mapping of Pinery-MISO Tube_Id

- pinery-lims-gsle/db/api-queries.sql
This change has already been made to plims3 and production GSLE (the queries are saved in GSLE; these are just copies)
> GLT-1443: updated GSLE order queries to include missing records

- pinery-lims-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java
- pinery-lims-miso/src/main/java/ca/on/oicr/pinery/lims/miso/converters/NonSampleTypeConverter.java
- pinery-lims-miso/src/test/java/ca/on/oicr/pinery/lims/miso/converters/NonSampleTypeConverterTest.java
This PR is for the GLT-1519 change only. Will merge GLT-1412 (https://github.com/oicr-gsi/pinery/pull/21) before this
> MISO schema update

- pinery-lims-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java
Depends on schema change in https://github.com/TGAC/miso-lims/pull/746
> GLT-1574: added volume field for MISO dilutions

- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultLaneProvenance.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultSampleProvenance.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/LimsAttribute.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/SampleAttribute.java
- pinery-service/src/main/java/ca/on/oicr/pinery/service/impl/DefaultSampleProvenanceService.java
This PR adds "pool_name" to the lane attributes of both sample and lane provenance.
> GP-1295 - Add "Pool Name" to pinery provenance lane attributes

- pinery-lims-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
> rename external institute ID to secondary ID

- pinery-lims-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
> GP-1324 - Update Pinery-MISO for MISO 0.2.88 schema changes

- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/FlatfileClient.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleDao.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleFileDao.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleProjectDao.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleProjectFileDao.java
- pinery-lims-flatfile/src/test/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleFileDaoTest.java
- pinery-lims-flatfile/src/test/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleProjectFileDaoTest.java
- pinery-lims-flatfile/src/test/resources/test-context.xml
- pinery-to-flatfile/src/main/java/ca/on/oicr/pinery/flatfile/Main.java
I've fixed this on the server with a symlink :disappointed:
> Fix project.tsv output name

- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/LimsSampleAttribute.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/LaneProvenanceResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/SampleProvenanceResource.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/LaneProvenanceResourceTest.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/SampleProvenanceResourceTest.java
> Export RIN and DV200 via sample provenance

- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/LimsSampleAttribute.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/LaneProvenanceResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/SampleProvenanceResource.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/LaneProvenanceResourceTest.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/SampleProvenanceResourceTest.java
- pom.xml
I also upgrade the formatter to fix that locking bug.
> Add donor sex to sample provenance

- .travis.yml
- pinery-api/src/main/java/ca/on/oicr/pinery/api/RunPosition.java
- pinery-api/src/main/java/ca/on/oicr/pinery/api/RunSample.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/RunFileDao.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultLaneProvenance.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRunPosition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRunSample.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultSampleProvenance.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/LimsLaneAttribute.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/LimsSampleAttribute.java
- pinery-to-flatfile/src/main/java/ca/on/oicr/pinery/flatfile/writer/SequencerRunWriter.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RunDtoPosition.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RunDtoSample.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/LaneProvenanceResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/SampleProvenanceResource.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/LaneProvenanceResourceTest.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/SampleProvenanceResourceTest.java
- pom.xml
* Run purpose
* Spike-in attributes
* Single cell attributes
> GLT-3071, GLT-3100, GLT-3101: added new attributes

- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/DaoUtils.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/RunFileDao.java
- pinery-lims-flatfile/src/main/java/ca/on/oicr/pinery/lims/flatfile/dao/SampleFileDao.java
- pinery-to-flatfile/src/main/java/ca/on/oicr/pinery/flatfile/writer/SequencerRunWriter.java
Flatfile format doesn't allow key/value pairs to be the value of a key/value pair
> fix pool and run-sample status format in flatfiles

- pinery-api/pom.xml
- pinery-client/pom.xml
- pinery-lims/pom.xml
- pinery-service/pom.xml
- pinery-ws-dto/pom.xml
- pom.xml
I've only included things that will be consumed as libraries.
> Add automatic module names to Pinery

- pinery-to-flatfile/README.md
> updated flatfile documentation

- pinery-ws-dto/pom.xml
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/LaneProvenanceDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/SampleProvenanceDto.java
- pom.xml
Replaces Apache commons libraries with inline code to have no external
dependencies for these modules.
> Remove dependencies on `pinery-api` and `pinery-ws-dto`

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Requisition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisition.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3680
> [GLT-3680] added 'stopped' field to requisitions

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Requisition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisition.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3852
> [GLT-3852] added requisition supplemental sample IDs

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Requisition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisition.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3862
> [GLT-3862] added requisition stop reason attribute

- pinery-api/src/main/java/ca/on/oicr/pinery/api/AssayTest.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultAssayTest.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/AssayTestDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3958
> [GLT-3958] added permitted samples assay test field

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Status.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultStatus.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/StatusDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3975
> [GLT-3975] added QC notes to samples and run-samples

- pinery-lims/pom.xml
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultSampleProvenance.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/SimpleSampleProvenance.java
- pinery-ws-dto/pom.xml
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/SampleProvenanceDto.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/SampleProvenanceResource.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/SampleProvenanceResourceTest.java
- pom.xml
Jira ticket: https://jira.oicr.on.ca/browse/GLT-3974
Requires Provenance API release and dependency update
> [GLT-3974] added batch IDs to V9 sample provenance

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Assay.java
- pinery-api/src/main/java/ca/on/oicr/pinery/api/AssayTargets.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultAssay.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultAssayTargets.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/AssayDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/AssayTargetsDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4011
> [GLT-4011] added assay turn-around time targets

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Requisition.java
- pinery-api/src/main/java/ca/on/oicr/pinery/api/RequisitionPause.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisitionPause.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionPauseDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4014
> [GLT-4014] added requisition pauses

- pinery-service/src/main/java/ca/on/oicr/pinery/service/impl/Cache.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4072
Anything that references samples should now be loaded before samples
> [GLT-4072] improved order of cache loading

- .vscode/settings.json
- pinery-api/src/main/java/ca/on/oicr/pinery/api/SampleProject.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/AttributeNameClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/ChangeLogClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/InstrumentClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/InstrumentModelClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/OrderClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/PineryClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/ProjectClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/ResourceClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/SampleClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/SampleTypeClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/SequencerRunClientTest.java
- pinery-client/src/test/java/ca/on/oicr/pinery/client/UserClientTest.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultSampleProject.java
- pinery-service/src/test/java/ca/on/oicr/pinery/service/impl/DefaultSampleProvenanceServiceTest.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/SampleProjectDto.java
- pinery-ws-dto/src/test/java/ca/on/oicr/ws/dto/DtosTest.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/LaneProvenanceResourceTest.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/ResourceTest.java
- pinery-ws/src/test/java/ca/on/oicr/pinery/ws/SampleProvenanceResourceTest.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4120
> [GLT-4120] added 'analysis review required' field to projects

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Requisition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisition.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4098
> [GLT-4098] change requisition assayId field to Set

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Requisition.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultRequisition.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/RequisitionDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GR-1526
> [GR-1526] added requisition created date

- pinery-api/src/main/java/ca/on/oicr/pinery/api/AssayTest.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultAssayTest.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/AssayTestDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4251
> [GLT-4251] added assay test tissue origin fields

- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/StatusController.java
- pinery-ws/src/main/webapp/WEB-INF/spring-servlet.xml
- pom.xml
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4259
> [GLT-4259] updated springfox-swagger library

- pinery-service/pom.xml
- pinery-service/src/main/java/ca/on/oicr/pinery/service/impl/Cache.java
- pinery-ws/README.md
- pinery-ws/pom.xml
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/AdminController.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/AssayResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/BoxResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/InstrumentResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/LaneProvenanceResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/OrderResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/RequisitionResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/RunResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/SampleProvenanceResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/SampleResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/StatusController.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/UserResource.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/component/DefaultExceptionHandler.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/component/PineryContextListener.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/component/RestError.java
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/component/SwaggerConfig.java
- pinery-ws/src/main/webapp/WEB-INF/spring-servlet.xml
- pinery-ws/src/main/webapp/WEB-INF/web.xml
- pinery-ws/src/test/resources/test-spring-servlet.xml
- pom.xml
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4285
> [GLT-4259] updated to Spring 6

- pinery-ws/README.md
- pinery-ws/src/main/java/ca/on/oicr/pinery/ws/component/SwaggerConfig.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4300
> [GLT-4300] fixed Swagger determining base URL; added manual override

- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultSampleProvenance.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4295
> [GLT-4295] mark skip true if consent is revoked

- .github/workflows/pinery_ci.yml
> update actions/cache to v4

- pinery-api/src/main/java/ca/on/oicr/pinery/api/Deliverable.java
- pinery-api/src/main/java/ca/on/oicr/pinery/api/SampleProject.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultDeliverable.java
- pinery-lims/src/main/java/ca/on/oicr/pinery/lims/DefaultSampleProject.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/DeliverableDto.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/Dtos.java
- pinery-ws-dto/src/main/java/ca/on/oicr/ws/dto/SampleProjectDto.java
Jira ticket: https://jira.oicr.on.ca/browse/GLT-4378
> [GLT-4378] refactored project deliverables to include additional fields
